### ISSUE TITLE
quip + GAP

### ISSUE THREAD

**Issue by g7dhaliwal** [libAtoms/QUIP#102]
Hi,

   I am a new user of GAP and finding certain difficulties with the command line interface. I am trying to train GAP potential for graphene data using distance_2b as descriptor. With the command line written below, I am getting the following error. I will really appreciate of any help on properly using GAP for training potentials.

command Line:  quip atoms_filename=Graphene_GAP_Training.xyz'gap={distance_2b' cutoff=4.1 n_sparseX=250 covariance_type=ard_se theta_fac=0.5: angle_3b cutoff=4.1 n_sparseX=500 covariance_type=ard_se theta_fac=0.5 'delta=0.1}' 'default_sigma={0.001' 0.05 0.01 '0.02}' sparse_jitter=1.0e-8 e0=0.0_

Error:
SYSTEM ABORT: quip_params.xml does not exist

**Comment by noambernstein** [comment]
You want the teach_sparse executable, not ‘quip’.  Also, check out the —help flag (double dash)

**Comment by g7dhaliwal** [comment]
Thanks. It worked . Unfortunately, I am getting the following error.

SYSTEM ABORT: Traceback (most recent call last)
File "/home/QUIP/src/libAtoms/System.f95", line 1316 kind unspecified
string_to_real: could not convert, iostat=5010

Will look through the --help to see if there is any inappropriate entry. Meantime, I will appreciate of the related help

**Comment by noambernstein** [comment]
First, check your quotes. Second, as the error message says, it’s expecting a real and can’t parse it. Probably e0, which has an extra underscore

**Comment by gabor1** [comment]
Your command line is full of extraneous quotes. Here is the command line that means the same thing, properly formatted. I put comments on your parameters below. 


teach_sparse atoms_filename=Graphene_GAP_Training.xyz gap={distance_2b cutoff=4.1 n_sparseX=250 covariance_type=ard_se theta_fac=0.5: angle_3b cutoff=4.1 n_sparseX=500 covariance_type=ard_se theta_fac=0.5 delta=0.1} default_sigma={0.001 0.05 0.01 0.02} sparse_jitter=1.0e-8 e0=0.0


However, you are missing a "delta" parameter from your distance_2b descriptor (you have one for the angle_3b descriptor). 

Your default_sigmas look too small, because you will never reach that kind of accuracy with just a 2-body and a 3-body term. 

n_sparseX has been renamed "n_sparse" now. 

Your n_sparse for the 2b is way too big, you don't need more than 15. 

Check out the command line for the published graphene potential https://journals.aps.org/prb/abstract/10.1103/PhysRevB.97.054303



-- Gábor

**Comment by noambernstein** [comment]
Gabor's right about the extraneous quotes, that's what I meant before but
didn't say explicitly enough, but I think he removed a few too many quotes
- each {.....} should be enclosed in one set of quotes.  I guess it's
possible that it's not mandatory, but I'm pretty sure it won't hurt.

     Noam

**Comment by g7dhaliwal** [comment]
Thanks Gabor. Can you please help me with Behler descriptor? I tried the following lines of code to access behler_g2 function
desc = descriptors.Descriptor('behler_g2 eta=0.4 rs=0 rc=4 ')

This gave me the following error 
descriptor_initialise found too few or too many IP Model types args_str='behler_g2 eta=0.4 rs=0 rc=4'

Thanks

**Comment by gabor1** [comment]
Um... where did you get this initialisation string? 

Our implementation is called "behler", not "behler_g2", and the parameters are hardcoded into descriptors.f95. We only used this for a quick test, and so didn't implement parametrising from the command line or python. But having looked at it, all the infrastructure is there, so it would be very easy to do that. 

-- Gábor

**Comment by g7dhaliwal** [comment]
Thanks Gabor. I went through the descriptor.f95 file and tried to initialize the descriptor string from the description of the fortran objects there. 

I used the 'behler' implementation but the number of columns of the descriptor array wasn't changing which I am assuming due to fixed hardcoded parameters. I will really appreciate if you can implement parameterizing of this descriptor from command line or python.

**Comment by gabor1** [comment]
I won't have time to do that in the near future, but feel free to have a go yourself! You can see where the eta rc and rs parameters are set (in the routine "behler_initialise"), perhaps in the meantime you can hardcode the parameters you want, and recompile. 

-- Gábor
