### ISSUE TITLE
Using gap to train graphene potential, met some problems

### ISSUE THREAD

**Issue by fkxie** [libAtoms/QUIP#110]
Hi,
Recently,I tried to follow the reference of "Development of a machine learning potential for graphene"  (Link:  https://doi.org/10.1103/PhysRevB.97.054303).
I used the graphene configurations' data offered by http://www.libatoms.org/Home/DataRepository.

In the reference, the 2B,3B,MB terms have different weighting factor δ ，separately.When I trained my model, I couldn't found any parameters related to δ in teach_sparse.So, how to deal with this problem?
And what's the standard to choose parameters of n_max(number of radial basis functions) and l_max(spherical harmonics basis band limit)?

Thanks,

**Comment by gabor1** [comment]
That's because the delta is specific to each descriptor within the gap string. Have a look at the command embedded in the xml file, (grep for "command").

The band limit is basically a convergence parameter. Higher limit, more expensive, but more accurate description of the neighbourhood. But depending on the complexity of that potential, you often don't need to go above 8 or 10 and sometimes you get away with 6. Also, the ratio of cutoff and atom_sigma tells you how much resolution you need

-- Gábor

**Comment by fkxie** [comment]
Hi,Gabor
Thanks a lot for your help.
I check the xml file and figure out that delta is exactly weighting factor of three terms.Previously,I was confused by the comments given by http://libatoms.github.io/QUIP/teach_sparse.html about delta, It says:"delta: Set the standard deviation of the Gaussian process. Typically this would be set to the standard deviation (i.e. root mean square) of the function that is approximated with the Gaussian process."

Maybe the comments on the delta need some revision?

**Comment by gabor1** [comment]
We will improve the documentation. But they are consistent. When you use multiple descriptors you are using multiple Gaussian processes to describe multiple functions which are added together to model the total energy

-- Gábor

**Comment by libAtomsBuildSystem** [comment]
Can I close the issue?

**Comment by fkxie** [comment]
Yeah,thanks.
please close it.
