### ISSUE TITLE
Weighting factor for different descriptors

### ISSUE THREAD

**Issue by Leeyenxie** [libAtoms/QUIP#112]
Hi,

Can I have any suggestions for how to choose the weight factor for different descriptors (delta)?

My method is training a small cluster  -->  plot error figure --> change weight factor --> training the cluster --> .... (loop).   But it seems time consuming and not efficient.

Is there any easier way to determine the weight factors？

Thank you , :D

Yen,

**Comment by gabor1** [comment]
Delta is an energy scale. In multi-kernel learning we start from the simple ones (2-body) and go up. At each stage you assess the error of the previous model, and use that as a guide for the energy scale of the next term you are trying to train. The only tricky business is that an energy scale does not necessarily translate directly into the delta value, because the delta value applies _per_descriptor_ whereas the energy range is usually given per_atom. One saving grace is that you don’t really need to nail the delta value - within a factor of 3 is fine, as you get more data it becomes less and less relevant. 

Let’s take an example. Suppose you are training to total binding energy (atomisation energy) of a system. 

1. You start with the two-body. You know from electronic structure theory that the energy of an atom-atom bond is a couple of eV. So this is a reasonable to start with, e.g delta=1.0 (eV). You train a two-body potential with this, and measure its RMS energy error per atom. Remember that this potential doesn’t need to be good at simulation yet, most of the job of the two-body is to capture the atom-atom repulsion and a little bit of the binding. 

2. Suppose the RMS error of your 2b potential is 0.5 eV/atom. Now you want to add three-body terms. You are asking the three-body terms to account for 0.5 eV per atom. How many three-body terms will there be that involve an atom? That depends on the cutoff, but this is misleading because second and further neighbours will contribute much less. So let’s stick with first neighbours. In a semiconductor like Si, there are 4 first neighbours, leading to 6 unique three-body terms, so a reasonable delta is about 0.1 eV, maybe a bit smaller. For a metal, there might be ~10 first neighbours, leading to 45 three-body terms, so the three-body delta should be ~ 0.01 !

3. If you want to add a SOAP descriptor, there is only one per atom, so you measure the error-per-atom of your previous potential (either 2b or 2b+3b) and use that error as the SOAP delta. 


I hope this helps! Let us know how you get on. 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory
Pembroke College
University of Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by Leeyenxie** [comment]
Hi,gabor

Thanks for your explicit explanation, it helps me walk forward on my work!

I think my method is not proper and unphysical after reading your explanation,which indeed helps me a lot.

Best wishes,
Yen,
