### ISSUE TITLE
AtomEye compilation error './libAtomEye.a: Permission denied'

### ISSUE THREAD

**Issue by chrisahart** [libAtoms/QUIP#121]
Hi,

I'm looking to use QUIP and GAP, however am having trouble compiling AtomEye following the instructions at https://github.com/jameskermode/AtomEye. When attempting to compile I get several library related permission errors including './libAtomEye.a: Permission denied'. 

This issue seems similar to one posted [recently](https://github.com/libAtoms/QUIP/issues/120) where they also had trouble compiling AtomEye. Hopefully this is just a simple problem with my method, however I'd greatly appreciate any help. 

I've provided the [makefile.config](https://github.com/libAtoms/QUIP/files/2803887/Makefile_config.txt) I used in addition to the compilation logs, for which the method was:

git clone https://github.com/jameskermode/AtomEye
export QUIP_ARCH=linux_x86_64_gfortran
export QUIP_ROOT=/scratch/cahart/software/QUIP
(edit makefile.config)
make ([log](https://github.com/libAtoms/QUIP/files/2804063/make_log.txt))
make clean
make atomeyelib ([log](https://github.com/libAtoms/QUIP/files/2804066/make_atomeyelib_log.txt)) 

Thanks,
Chris

**Comment by gabor1** [comment]
Actually I thin your compile succeeded. Those “permission” errors are makefile script errors I *think* because you don’t have $AR defined, but these errors are not fatal. You should find the executable in the bin.

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory
Pembroke College
University of Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by chrisahart** [comment]
Thank you for your help, the compilation had indeed succeeded.

For future reference, what exactly are you referring to in regards to defining $AR?

**Comment by gabor1** [comment]
the “ar” command, for library archive manipulation. I had seen these errors before, but never bothered to track them down because the compilation actually worked… but yes I agree that it throws you off when you see it. 

> On 1 Feb 2019, at 16:35, chrisahart <notifications@github.com> wrote:
> 
> Thank you for your help, the compilation had indeed succeeded.
> 
> For future reference, what exactly are you referring to in regards to defining $AR?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 


-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory
Pembroke College
University of Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/
