### ISSUE TITLE
Build error with gfortran_openmpi

### ISSUE THREAD

**Issue by vsumaria** [libAtoms/QUIP#136]
I was trying to install using the linux_x86_64_gfortran_openmpi architecture. But in the "Making Programs" step, I am getting the following error:
......
./libatoms.a(lbfgs.o): In function `lbfgs_':
ccb794gU.f:(.text+0xd1): undefined reference to `s_wsfe'
ccb794gU.f:(.text+0xd8): undefined reference to `e_wsfe'
ccb794gU.f:(.text+0x18e): undefined reference to `s_wsfe'
ccb794gU.f:(.text+0x1cc): undefined reference to `s_wsfe'
ccb794gU.f:(.text+0x1d3): undefined reference to `e_wsfe'
ccb794gU.f:(.text+0x4a5): undefined reference to `s_wsfe'
ccb794gU.f:(.text+0x4bf): undefined reference to `do_fio'
./libatoms.a(lbfgs.o): In function `quiplb1_':
ccb794gU.f:(.text+0xc01): undefined reference to `s_wsfe'
ccb794gU.f:(.text+0xc17): undefined reference to `do_fio'
.......

Can someone help me.

**Comment by vsumaria** [comment]
When I just used Makefile.linux_x86_64_gfortran file, I didn't get this error

**Comment by gabor1** [comment]
These sound like system libraries, so either your mpi compiler is not set up correctly, or you are not using them correctly (e.g. you don’t have the right include paths, you don’t include the correct libraries in your linking step etc). There is very little we can do to help you out with that. I suggest you consult someone who knows how to compile software in parallel on your machine. 

In addition, you could reassess whether you really need QUIP compiled with MPI. for using our potentials, I recommend running them through our LAMMPS plugin, so in that scenario you compile QUIP in serial, and LAMMPS does all the parallelisation. For training potentials, you can use the thread parallelisation thtough OpenMP rather than MPI - there is no advantage of doing with via MPI because our potential fitting code is not data parallel, so you wouldn’t want to run it on more than one node anyway. 

Gabor

> On 16 Jul 2019, at 01:51, vsumaria <notifications@github.com> wrote:
> 
> I was trying to install using the linux_x86_64_gfortran_openmpi architecture. But in the "Making Programs" step, I am getting the following error:
> ......
> ./libatoms.a(lbfgs.o): In function lbfgs_': ccb794gU.f:(.text+0xd1): undefined reference to s_wsfe'
> ccb794gU.f:(.text+0xd8): undefined reference to e_wsfe' ccb794gU.f:(.text+0x18e): undefined reference to s_wsfe'
> ccb794gU.f:(.text+0x1cc): undefined reference to s_wsfe' ccb794gU.f:(.text+0x1d3): undefined reference to e_wsfe'
> ccb794gU.f:(.text+0x4a5): undefined reference to s_wsfe' ccb794gU.f:(.text+0x4bf): undefined reference to do_fio'
> ./libatoms.a(lbfgs.o): In function quiplb1_': ccb794gU.f:(.text+0xc01): undefined reference to s_wsfe'
> ccb794gU.f:(.text+0xc17): undefined reference to `do_fio'
> .......
> 
> Can someone help me.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 


-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory
Pembroke College
University of Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by vsumaria** [comment]
On having googled the issue a little, I changed F77=gfortran from F77=mpif77 and that seems to have worked. My jobs are running in parallel threads now. 

I actually had one more question for using gap_fit on such clusters. How do you restart a gap_fit job which might have ended due to time restrictions? Does the same command in the folder continue training ?

**Comment by gabor1** [comment]
You cannot restart gap_fit. 

-- Gábor

**Comment by vsumaria** [comment]
That's is what I thought, since there was no documentation stating anything otherwise. 

The .xml file does get updated when the job is running, so there is no way to use it unless the job is completed then, right ?

**Comment by gabor1** [comment]
Correct

-- Gábor

**Comment by vsumaria** [comment]
Alright. Closing the issue. Thanks

**Comment by vsumaria** [comment]
I have compiled QUIP+GAP with openmpi. 

But when I try to run a gap_train command on more than one processor (exclusively on the same node), I get a "BAD TERMINATION", "EXIT CODE: 9" error. 

What am I doing wrong here?

**Comment by gabor1** [comment]
Sorry. The gap_fit program does not run across nodes (it is not data parallel). It is parallelized with threads.

The quip program runs with mpi . 

-- Gábor

**Comment by vsumaria** [comment]
I am running the command on the same node (exclusively one node), on parallel processors. I still get that error.

**Comment by gabor1** [comment]
If you are content running on one node, don't use mpi for gap_fit but use the openmp makefile, that will parallelize it using threads 

-- Gábor

**Comment by vsumaria** [comment]
Alright, will give it a try.

**Comment by gabor1** [comment]
any luck here?
