### ISSUE TITLE
incompatibility with written ASE extxyz because of 6-element stress field

### ISSUE THREAD

**Issue by noambernstein** [libAtoms/QUIP#14]
If an atomic config generated using ASE with a stress is written as an extxyz, it has a 6 element stress field written, rather than a 9-element as quippy expects.  This extxyz file can therefore not be read in by quip (as an xyz).

P.S. - it would be nice if convert.py, and others, recognized extxyz as a valid suffix.

**Comment by jameskermode** [comment]
I just started trying to fix this and it's not obvious how to proceed. We can't simply convert all 6-element vectors to 3x3 matrices on reading, as the Voigt convention for off-diagonal entries differs by a factor of two between stresses and strains, so we'd have to make some assumptions from the name of the key about how to convert the corresponding value. We could convert keys starting with (or containing?) "stress" as stresses and those starting with or containing strain as strains?

Alternative is to change the ASE writer to always write 3x3 matrices. I think this is probably a better solution.

Second part of request is fixed in commit 7b1e2f2b3, pushed to gc121repo and should make it to github overnight tonight.

**Comment by noambernstein** [comment]
> On Aug 12, 2015, at 10:05 AM, James Kermode notifications@github.com wrote:
> 
> I just started trying to fix this and it's not obvious how to proceed. We can't simply convert all 6-element vectors to 3x3 matrices on reading, as the Voigt convention for off-diagonal entries differs by a factor of two between stresses and strains, so we'd have to make some assumptions from the name of the key about how to convert the corresponding value. We could convert keys starting with (or containing?) "stress" as stresses and those starting with or containing strain as strains?
> 
> Alternative is to change the ASE writer to always write 3x3 matrices. I think this is probably a better solution.

I think this latter choice makes sense. From ASE's point of view, the stress is a special variable, not just some random field.  In the same way that you had to pick particular field names for the other quantities, it's reasonable to assert that in extxyz the stress is 3x3 and called "stress", and promote it from ASE's 6x1 to 3x3 upon writing.

 Thanks.
Noam

**Comment by jameskermode** [comment]
Fix committed to ASE trunk - https://trac.fysik.dtu.dk/projects/ase/changeset/4654
