### ISSUE TITLE
segmentation error + 3-element model + sparse_separate_file=F

### ISSUE THREAD

**Issue by lipai-ustc** [libAtoms/QUIP#225]
Dear Prof.
I'd like to report an error I encountered. Recently I use GAP to train a 3-element model containing Li, Cl, O elements. It seems OK for the training process, but it gives segmentation error when I use quip or quippy in python with this xml potential. The gap_fit parameters are as follows:
```
gap_fit at_file=all.xyz \
        force_parameter_name=forces \
        gap={ soap cutoff=5.0 \
          atom_sigma=0.5 \
          l_max=6 \
          n_max=10 \
          delta=0.5 \
          covariance_type=dot_product \
          zeta=4 \
          n_sparse=400 \
          add_species=T \
          sparse_method=cur_points} \
e0={Li:0:Cl:0:O:0} \
default_sigma={0.010 0.20 0.0 0.0} \
do_copy_at_file=F sparse_separate_file=F \
gp_file=gap_soap.xml 2>&1 | grep -v FoX 
```
I found that if the training set size is as low as 25 structures (50 will give the error), or I set sparse_separate_file=T, it will be fine without error. Besides, I saw it somewhere that the sparse_separate_file=T setting would speed up the calculation. 
Do you know why this error happens? Why it's better to use sparse_separate_file=T?

**Comment by gabor1** [comment]
have you tried setting "ulimit -s unlimited" when you run  it? In general for trainings that include SOAP, I would always use sparse_separate_file=T, because otherwise your XML file is going to be enormous, and the Fortran XML parser will be very slow, and possibly also run out of memory. When you turn this option on, you will get additional files next to your basic XML file, and you need to carry those around in the same directory when you use the model

Your default energy sigma of 10 meV/atom is quite high, and your default force sigma of 0.2 as well - I would normally use such settings for high temperature liquid configurations (thousands of degrees K). you are not using any 2-body descriptors in addition to SOAP, so your model will be in danger of atoms coalescing and giving you nonsense unless your input data contains a few configurations with very small interatomic distnaces. 2-body descriptors extrapolate much better (because they only need to do this in one dimension) to small interatomic distances.

**Comment by gabor1** [comment]
We often use a "baseline" model that is just a simple repulsive pair potential to take care of this problem (see the 2018 PRX paper on silicon)

**Comment by lipai-ustc** [comment]
Yes, Prof., I also tested the setting "ulimit -s unlimited". It also reports the segmentation error with just 50 structures where each one contains just 31 atoms. This is not a big problem for me since it runs OK with "sparse_separate_file=T". 

Thank you for your reminder. Here I only have high T training set and it does not raise coalescing problem. I just use this GAP to run MD for generating more structures as input of VASP. After I have a large enough ab initio training set, I use a GAP including 2b/3b/soap. BTW, the final GAP parameters are as follows, and my training set has about 1000-2000 structures. Can you give any comment on it?
```
./gap_fit at_file=final.xyz \
force_parameter_name=forces \
gap={ distance_2b n_sparse=15 theta_uniform=1.0 sparse_method=uniform covariance_type=ard_se cutoff=4.0 delta=1.5 add_species=T:\
angle_3b n_sparse=200 theta_uniform=1.0 sparse_method=uniform covariance_type=ard_se cutoff=3.5 delta=0.01 add_species=T:\
soap cutoff=5.5 atom_sigma=0.5 n_max=10 l_max=6 delta=0.02 covariance_type=dot_product zeta=4 n_sparse=2000 sparse_method=cur_points add_species=T} \
e0={Li:0.0:Cl:0.0:O:0.0} \
default_sigma={0.008 0.01 0.0 0.0} \
do_copy_at_file=F sparse_separate_file=T \
gp_file=gap_final.xml
```

**Comment by gabor1** [comment]
OK. I wouldn’t just do one iteration like this, but a couple - so make your 2b/3b/soap, run more MD, fold back some of those into the training. This also means that I wouldn’t aim to get so many (1000-2000) structures right in the first iteration, but pace it a bit more, maybe 100-200 each iteration. you mauy find that you don’t need 2000! 

Your command looks good, except that your default energy sigma (0.008) is really high given your default force sigma. For a very accurate model, I would use {0.001 0.05 0.05 0.0}. BTW why are you not using the stresses ? The 0.01 force sigma will absolutely be way too small for high energy configurations. We typically use config_types, to group configurations, and give different sigmas to low energy/low temperature configs and to high energy configs (again see PRX Silicon paper). If you *don’t* do this, then your low temperature stuff won’t be accurate enough I think. 

make sure you use a decent enough electronic smearing, and that you use the free energy rather than the energy output from VASP, as that is the one consistent with the forces. 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by lipai-ustc** [comment]
Thank you Prof. for your suggestions. I will try to adjust the sigma parameters and also use the config_types  setting. BTW, I'd like to  confirm that the free energy in OUTCAR of vasp corresponds to the term "free energy TOTEN".

**Comment by gabor1** [comment]
yes, "free energy TOTEN" is what you want. if you are parsing the OUTCAR using ASE (which I highly recommend, it takes care of the units properly, including the sign of the stress!) then pass the "force_consistent=True" keyword to the get_potential_energy() function, and you will get the free energy. 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by lipai-ustc** [comment]
I use a homemade bash script for the parsing. I will also test the ASE package for this.

**Comment by gabor1** [comment]
when you add stresses (which you should), remember that we need the virial stress, which is stress * volume, in units of eV. 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by lipai-ustc** [comment]
OK. I will check my results with the results parsed with ASE. If the latter is more convenient I will use it directly. Many thanks!
