### ISSUE TITLE
Dimension of the SOAP vector

### ISSUE THREAD

**Issue by zyt0y** [libAtoms/QUIP#241]
Hi,

The dimension of the SOAP vector is defined in `soap_dimensions()` in `GAP/descriptors.f95`, which is `(l_max+1) * ( (n_max*n_species)*(n_max*n_species+1) ) / 2 + 1`.  Why is `+ 1` included in the end? I have also checked the SOAP implementation in [Dscribe](https://github.com/SINGROUP/dscribe/blob/master/dscribe/descriptors/soap.py#L386) which does not have `+ 1`.

Best,
Zeyuan

**Comment by mcaroba** [comment]
If I recall correctly, the last number is used for the generalized version of the dot-product kernel: Eq(46) in https://onlinelibrary.wiley.com/doi/pdf/10.1002/qua.24927

**Comment by zyt0y** [comment]
> If I recall correctly, the last number is used for the generalized version of the dot-product kernel: Eq(46) in https://onlinelibrary.wiley.com/doi/pdf/10.1002/qua.24927

Looks reasonbale. Does this mean the last number is only useful for the polynomial kernel (eq-46), but meaningless for other types kernels like the squared exponential? I have also noticed that the value of last dimension is always zero.

**Comment by mcaroba** [comment]
As far as I understand it, in GAP descriptors and covariance functions are completely indepedent. So if your SOAP vector has dimensions n+1 the covariance function routines will work in that extended space. But if your last number is zero for all SOAP descriptors, then there is no impact whatsoever on the value of the kernel, either computed with the dot-product or squared exponential covariance functions (because all the squared distances for the (n+1)th component are always zero).

**Comment by zyt0y** [comment]
> As far as I understand it, in GAP descriptors and covariance functions are completely indepedent. So if your SOAP vector has dimensions n+1 the covariance function routines will work in that extended space. But if your last number is zero for all SOAP descriptors, then there is no impact whatsoever on the value of the kernel, either computed with the dot-product or squared exponential covariance functions (because all the squared distances for the (n+1)th component are always zero).

I understand what you are saying and agree that descriptors and covariance functions should be completely indepedent. As for the generalized version of the dot-product kernel in Eq(46), why not only modifying the covariance function and removing the (n+1)th component of SOAP vector? Are there any other reasons to keep the (n+1)th component and leave its value to be zero?

**Comment by gabor1** [comment]
it hasn’t really bothered anyone before...

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by zyt0y** [comment]
This does not affect my usage of QUIP and GAP. I am just curious why the (n+1)th component is included during the development of the code.

**Comment by gabor1** [comment]
Albert Bartok-Partay is your man to answer that question. 

-- Gábor

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/

**Comment by mcaroba** [comment]
I think the reason is more or less obvious. If you want to introduce the extra term as part of the covariance function, then making this term atom-dependent means that you need to provide, effectively, another descriptor. So now your covariance function takes two descriptors per atom instead of one. From the logic of how these computations are done, and how descriptors and covariance functions can be combined flexibly, it makes a lot more sense to keep it the way it is.

**Comment by zyt0y** [comment]
I found the [commit log](https://github.com/libAtoms/QUIP/commit/7f42d398532c990c7b1f23e746ab7651c34ffeaa) of introducing (n+1)th component which has the value of covariance_sigma0 defined in Eq(46). From my understanding of the code, the default value of covariance_sigma0 is zero (this is why I have seen the last element of SOAP vector is zero), so that is has no effects no matter which covariance function is chosen. If one assigns covariance_sigma0 a non-zero value, the last element of descriptor will vanish in the squared exponetial covariance function Eq(45) since covariance_sigma0 is a global parameter and atom independent. When a non-zero covariance_sigma0 is combined with the generalized version of the dot-product kernel in Eq(46), it will become covariance_sigma0^2 as it should do. The trick of keeping (n+1) dimension is just for easier implementation of Eq(46) without destroying the usage of SOAP vector itself and its combination with other covariance functions.

**Comment by jameskermode** [comment]
as Gabor says, @albapa can probably shed light on this

**Comment by albapa** [comment]
As stated above, the purpose of the last element so we can specify a sigma_0, as described in 4.2.2 in C. E. Rasmussen & C. K. I. Williams, Gaussian Processes for Machine Learning, the MIT Press, 2006. As the default is zero, I do not see how it would affect any application of the descriptor, whether as a dot-product or a distance, as used in the squared exponential kernel. To include it in the descriptor rather than the kernel definition is a design choice that is purely practical. So far it hasn't been a limitation.

**Comment by zyt0y** [comment]
@albapa Thanks for your clarification :)
