### ISSUE TITLE
Quip can not predict accurate total energy with the MLFF of phosphorus

### ISSUE THREAD

**Issue by ML-EF** [libAtoms/QUIP#322]
Hi,
I download the trained potential file(P_GAP_20.xml) form https://zenodo.org/record/4003703#.YP6DNLUzbIU.  I just use QUIP  to predict the total energy with some structures from the training dataset (P_GAP_train_data.xyz). This should not be a problem. But the predicted total energies have a big deviation from the DFT values listed in the trainning dataset as shown in the figure.   Has the GAP code been changed greatly from the version used to train the phosphorus?   Thanks.
Yuqiang
![00](https://user-images.githubusercontent.com/25586920/126974246-5d14fd52-eadf-41de-b7d5-06f29f43e516.jpg)

**Comment by mcaroba** [comment]
I'm taking a look at this, but so far everything looks good (I will update when all the tests have run). In the meantime, which QUIP and GAP versions are you using?

**Comment by ML-EF** [comment]
> I'm taking a look at this, but so far everything looks good (I will update when all the tests have run). In the meantime, which QUIP and GAP versions are you using?

Hi, I just compiled the GAP and QUIP in the github with the makefile, I run the gapversion, it show "0".  Do I need to set the GAP or QUIP version during the compilation?  If so, how to do it?  Thanks.

**Comment by mcaroba** [comment]
It looks like you may not have GAP installed. When you clone the repo, make sure to use the `--recursive` flag so that git also retrieves the GAP files. Then, during the `make config` step, make sure that you say "yes" to building with GAP support.

Just for the record, this is the agreement I get between training data and predicted values:

_(Note, there was a mistake in the figure I originally pasted here)_
![image](https://user-images.githubusercontent.com/14923880/127098828-8c4ff2d1-3851-41f3-932e-e25e9008774e.png)

So all good. I'm closing this issue since it's not related to the title. If your issues with the **installation** persist, please feel free to open a new issue.
