### ISSUE TITLE
new pypi release

### ISSUE THREAD

**Issue by bernstei** [libAtoms/QUIP#326]
Since things like the workflow do their CI using the pypi version, we should release a new one that includes the latest merged PRs, in particular the one that enables 6-element stress on the comment line for improved ASE compatibility.  I assume this is already in the works, but this issue is just to remind us.

**Comment by jameskermode** [comment]
This took me longer than it should have to sort out today, due to the shell script tests that I insisted on failing in the wheel-building CI (since the required `convert` binary is not available), but eventually it's working and v0.9.8 is on its way to PyPI now

https://pypi.org/project/quippy-ase/0.9.8/
