### ISSUE TITLE
mismatching descriptors when reading in sparse files in second run (MPI case) 

### ISSUE THREAD

**Issue by gabor1** [libAtoms/QUIP#570]
The attached zip contains a failed gap_fit run in the gap_new directory. The problem is that when gap_fit is run the first time to make the sparse files, it automatically reduces the number os sparse points to the max of the requesting and existing descriptors. then when it is run the second time, with the same number of requested descriptors, it is not finding them in the sparse file (because some of them got reduced) so it complains and stops. 

I suggest that in the short term, when sparse points are read in from file, the requested number should be just ignored, since the sparse points are requested to be read from the file, so who many we request is irrelevant. 

in the longer term, it would be really good to eliminate this double-run situation altogether. the sparse selection can be done on the root node only, so no mpi comm manipulation is needed.  
[gap_test-1.zip](https://github.com/libAtoms/QUIP/files/11278022/gap_test-1.zip)

**Comment by jameskermode** [comment]
@Sideboard please could you take a look at this?

**Comment by Sideboard** [comment]
Thanks for the files!

In December I added the early counting of `n_sparse` from the sparse files so that the memory estimate works even if the descriptor is missing that argument. The check was introduced to prevent accidental calculation with a different configuration than the user anticipated. The check is skipped if `n_sparse` is 0 or missing (defaults to 0). I think this is the better option but if there is an agreement that it should be ignored, I can remove the check.

The single-run solution is more complicated since the sparse points are determined relatively late but the splitting of the frames is done early. I suggest we discuss this more in #548.

**Comment by gabor1** [comment]
so basically if we delete the "nsparse" directive in the second run, then it will work as before?

**Comment by Sideboard** [comment]
Yes. It will infer the value from the files. And since there is no mismatch, there is no error.

Please let me know if it does not work.

**Comment by gabor1** [comment]
thanks.
