### ISSUE TITLE
LAMMPS+QUIP+GAP not working on more than one processes

### ISSUE THREAD

**Issue by pastewka** [libAtoms/QUIP#66]
When running GAP via the LAMMPS wrapper, we get the following error when using GNU compilers:

```SYSTEM ABORT: proc=1 IPModel_GAP_read_params_xml: invalid param_str length 0```

This can be traced back to src/Potentials/Potential.f95, line 459

```call initialise(io, trim(string(param_file_basename)), INPUT, master_only=.true.)````

Removing `master_only=.true.` gives a version of LAMMPS+QUIP+GAP that runs. I suspect that this problem also exists for other potentials than GAP.

**Comment by albapa** [comment]
Hi Lars, what was your QUIP_ARCH?

**Comment by noambernstein** [comment]
> On May 4, 2017, at 4:14 AM, albapa <notifications@github.com> wrote:
> 
> Hi Lars, what was your QUIP_ARCH?
> 
Just to make this point more explicit, normally LAMMPS handles all the parallelism, so QUIP needs to be compiled in serial.

    Noam

**Comment by pastewka** [comment]
This was then the problem. I used linux_x86_64_gfortran_openmpi. Will test if it works serially and then close this issue.

Is GAP OpenMP parallel and does it scale reasonably?

Lars

> Am 04.05.2017 um 13:01 schrieb noambernstein <notifications@github.com>:
> 
> 
>

**Comment by albapa** [comment]
I'll put a check in the wrapper to catch this with a meaningful error message.

Regarding your question on parallelisation:
QUIP on its own can do:

- serial
- OpenMP: not too bad, depends on the shared memory architecture, but don't expect terrific scaling above 8 cores.
- MPI: scales OK, but for large systems LAMMPS is the way to go - because of domain decomposition.

QUIP+LAMMPS: QUIP in serial, LAMMPS in parallel as usual. Used on several hundreds of cores, works well.

No mixed parallelism for any of the combinations above. I hope this helps.

**Comment by laigner** [comment]
Hey, I get the answer that I need a serial QUIP version for parallel LAMMPS. But is there a way for a coexistence of both versions. My problem is, I want to train my GAP model and validate it in parallel, because it is much faster. Further, I want to run a LAMMPS simulation with his GAP model in parallel. That is why I would need a parallel version of QUIP and a parallel version of LAMMPS in a coexisting way. Does anyone know a good solution to this?

**Comment by jameskermode** [comment]
OpenMP parallelisation of QUIP should combine fine with MPI parallelisation in LAMMPS. You may need to disable OpenBLAS threads with `export OPENBLAS_NUM_THREADS=1`

**Comment by gabor1** [comment]
you need two separate compilations of QUIP/GAP. the parallel one you can use to fit, but for use with lammps you MUST compile QUIP/GAP in serial. The model is the same of course, you will get identical answers.

the reason for this is that lammps does not pass the MPI communicator or thread information to the QUIP library, so the latter must run in serial.

— Gábor

Gabor Csanyi
Professor of Molecular Modelling
Engineering Laboratory
University of Cambridge

------- Original Message -------

**Comment by gabor1** [comment]
But in this case you may want to set the number of MPI tasks to be less than your available number of cores...

— Gábor

Gabor Csanyi
Professor of Molecular Modelling
Engineering Laboratory
University of Cambridge

------- Original Message -------

**Comment by jameskermode** [comment]
Yes indeed. The product of `OMP_NUM_THREADS` and the number of MPI processes should be equal to the total number of cores requested. Typically using up to about 12 threads gives good scaling for GAP evaluation.

**Comment by laigner** [comment]
> you need two separate compilations of QUIP/GAP. the parallel one you can use to fit, but for use with lammps you MUST compile QUIP/GAP in serial. The model is the same of course, you will get identical answers. the reason for this is that lammps does not pass the MPI communicator or thread information to the QUIP library, so the latter must run in serial. — Gábor Gabor Csanyi Professor of Molecular Modelling Engineering Laboratory University of Cambridge
> […](#)

Actually I tried this, with two separated compilations. Then when using the model with GAP I got the error that the database was build with another code version and I should update my code. I don't know, if this is a linking problem with LAMMPS and QUIP or if the open_mp version of quip produce a different output then the serial version.

**Comment by albapa** [comment]
You must have updated your code in the meantime. Compile serial QUIP again and relink it to LAMMPS.
