### ISSUE TITLE
Questions on gap_fit tutorial

### ISSUE THREAD

**Issue by Eadedeji** [libAtoms/QUIP#660]
I am new to GAP and am learning from the H2O tutorial. My training data is generated with ASE using the EMT calculator. I aim to reproduce the results and understand all parameters in detail, knowing that ASE data with EMT is purely for demonstration. The following are my questions/observations. 

Observations
1. When running gap_fit from the tutorial, I noticed that the "number of target virials" is 0. However, following the procedure, "virials " seem to be included in my training data; as a result, I was getting the error below:
<img width="612" alt="image" src="https://github.com/user-attachments/assets/1fd51667-4bed-4c54-838b-5e8117acd3e5">

from tutorial
<img width="688" alt="Screenshot 2024-07-24 at 6 03 09 PM" src="https://github.com/user-attachments/assets/82660cce-4d6d-4462-9971-2aefa2f79d2c">
So I changed the default_sigma from {0.008 0.04 **0** 0} to {0.008 0.04 **0.01** 0} for gap_fit to run successfully for both 2b and 2b+3b. See the plots below:
for 2b
<img width="884" alt="image" src="https://github.com/user-attachments/assets/ed12c437-0407-479b-b0e2-cb698ba96fb0">
for 2b+3b
<img width="926" alt="image" src="https://github.com/user-attachments/assets/75386113-8234-4fa4-87ec-67f2b0cc39b4">

2. I also noticed that the training and validation data (train.xyz and validate.xyz) trajectories, energy, etc., differ each time they are generated using ASE with EMT. 

Questions
1. Is there a seed number to generate or a way of generating training data that is the same as the one used in the tutorial?
2. What must I do if I want to exclude "virials" from the training data? Will doing this help me reproduce the result from the tutorial?
4. What do you think about my 2b and 2b + 3b plots? What parameters can I change to optimize the result?
5. what is the range of acceptable RMSE values for energy, forces (and perhaps virials)? 

I would greatly appreciate your reply. Many thanks 
Elijah

**Comment by gabor1** [comment]
The number of target viral is not 0, but 378, this is shown in your output. this is why you cannot have the viral sigma as zero. 

1. this is more of an ASE question. I don't think we saved the seed for the tutorial data. 
2. you can change the viral key name to something else that is not in the xyz file (like "dummy") and then the viral won't be read. 
3. your 2b and 2b+3b plots look okay  - water is not well fit with just 2b+3b
4. what is acceptable is in the eye of the beholder - or modeller. what you need for an accurate reproduction of the target potential energy surface properties depends on the temperature of your simulations. for room temperature, you want energies. to be at most a few meV/atom, and forces to be less than 50 meV/A, (certainly lower than 5% relative force error), for virals 10-50 meV/atom. in order to reach these accuracies you need to ensure that your training data is has this accuracy (e.g. convergence with respect to k-points and other parameters)

**Comment by gabor1** [comment]
generally your sigmas can't be lower than your data accuracies, and the accuracy you can expect from the GAP model can't be lower than the sigmas you give

**Comment by Eadedeji** [comment]
Thank you for the clarification. I appreciate it. I will now apply SOAP to H2O and observe the results.
