### ISSUE TITLE
How to include hand-picked structures in the GAP model?

### ISSUE THREAD

**Issue by hhlim12** [libAtoms/QUIP#666]
Dear QUIP developers, 

Thank you so much for the development of the wonderful package.
We are currently using the package to train the ML potential for systems involving chemical reactions.
Upon testing our model on transition state (TS) structures, we found that the performance was not good, especially in the TS region.
We think that we might miss those TS structures in the database and thus we perform NEB calculation and intend to include them in the training set.

However, it seems that due to the sparsification strategy using CUR decomposition, there is no guarantee that these hand-picked TS structures are considered during the training. Is it possible to bypass the CUR decomposition and manually include the TS structures in the database? Or is there any alternative for this?

Thank you in advance!

**Comment by bernstei** [comment]
That is not how the CUR sparsification works, because it applies to sparse (representative) points, not fitting structures.  _All_ data points are considered during training, in the sense that the error on them is part of the quantity that's minimized.  You can think of the CUR sparsification of the basis.  It's true that CUR is not a guarantee of the optimal set of sparse points - that's just a heuristic.  But all the data is considered.

That said, I think there is a way of manipulating the choice of sparse points, but I've forgotten the syntax.  Perhaps someone who's more familiar with that will chime in.

**Comment by hhlim12** [comment]
Thanks for a great explanation !. I now see that all the points are considered during the training. But I wonder whether I can put some weight on the training points of those TS structure... I'm using the SOAP Turbo but could not find such a parameter. I'm thinking of just putting some noise on the TS structure to generate more similar data points but it causes additional computational time for DFT and training...

**Comment by bernstei** [comment]
In the extxyz header (equivalent to `atoms.info`) you can put an energy/force/virial sigma, which is like an inverse to the weight, which overrides the `default_sigma`. I think the names are `energy_sigma`, `force_sigma`, and `virial_sigma`.  If it worked I think it prints out a summary of per-config sigmas in stdout.  You can just lower it for the TS structures.

**Comment by hhlim12** [comment]
Thanks for the great suggestion!  I definitely will try it.

**Comment by hhlim12** [comment]
Hi, I'd like to inform you that your suggestion works! The accuracy for the weighted structures increased. Thanks so much!
