### ISSUE TITLE
Documentation failing to build on Travis

### ISSUE THREAD

**Issue by tdaff** [libAtoms/QUIP#92]
It was working yesterday, but now fails with a cryptic error.

```
/home/travis/build/libAtoms/QUIP/doc/real_space_covariance.rst:67: WARNING: toctree references unknown document u'quippy.real_space_covariance.RealSpaceCovariance.covariance'
/home/travis/build/libAtoms/QUIP/doc/real_space_covariance.rst:67: WARNING: toctree references unknown document u'quippy.real_space_covariance.RealSpaceCovariance.is_same_fortran_object'
Traceback (most recent call last):
  File "/opt/python/2.7.14/lib/python2.7/logging/__init__.py", line 872, in emit

```

Have been unable to reproduce locally. Looks like the code (including GAP) hasn't changed at all and I can't see any changes to the build environment.

**Comment by max-veit** [comment]
The logfiles aren't showing us the actual error emitted by `build_docs.sh`. All the failed builds show the first one or two lines of this traceback right around the `real_space_covariance` warnings, then the script fails, goes straight to the `sleep` that fails the build, and we never get to see the output. And no, it's nothing to do with the `toctree` warnings or the missing `patch_f2py` module; those messages are in the successful build logs too. This is an infuriating error indeed.

Since we still have no idea what's causing this, I've temporarily disabled the nightly build to stop spamming everyone's inboxes with incessant spurious error notifications. Suggestions for further diagnosis are welcome.

**Comment by tdaff** [comment]
Looks like this was an issue with Travis not being able to keep up with the rate of terminal output.

Multiple solutions added in 7c7c5d793f323aebc5d90647f2b646028ae9060c but working fine by just adding `python -c "import fcntl; fcntl.fcntl(1, fcntl.F_SETFL, 0)" 20f4c2248e6ea18608cf9aaa5037b11fbe982fcc.
