### ISSUE TITLE
Missing _descriptors.py file

### ISSUE THREAD

**Issue by AndreasLeitherer** [libAtoms/QUIP#95]
Dear all, 

When loading the module "descriptors" via  "from quippy import descriptors",  the descriptors.py module is trying to import a  _descriptors.py file that it is not existing - but maybe I did not install some requirement? Thank you very much,

Best regards

Andreas Leitherer

**Comment by bartolsthoorn** [comment]
I have the same issue, it's really weird.

**Comment by bartolsthoorn** [comment]
It looks like the descriptors are dependent on GAP (mentioned here https://libatoms.github.io/QUIP/descriptors.html). GAP is a piece of code not included by default because of annoying licensing. (you can include it in `make config`)

Normally you should be able to download it here: www.libatoms.org/gap/gap_download.html but it looks like the website is down at the moment.. (ref #97 )

**Comment by gabor1** [comment]
You can get the latest gap source from the libatomsquip docker from dockerhub 

Our server room here is down for electrical maintenance

-- Gábor

**Comment by bartolsthoorn** [comment]
OK thank you for the quick reply, I will check it out!

**Comment by gabor1** [comment]
The docker has everything compiled and installed, all should work. There is a singularity version for hpc.

-- Gábor

**Comment by bartolsthoorn** [comment]
Yes thank you, it works.

Accepting the license agreement by entering an email address gives a 503 error, but it's fine because the python notebook boots up as expected and `quippy.descriptors` is present :+1:
